"""
Unit tests for PPTX export service.
Tests that JSON→PPTX conversion works for all layout types.
"""

import pytest

from app.models.slide import (
    Presentation,
    PresentationMetadata,
    Slide,
    SlideLayout,
    HighlightNumber,
    TableData,
    Columns,
    ContentBlock,
    ContentBlockType,
)
from app.services.pptx_service import generate_pptx


@pytest.fixture
def sample_presentation():
    """A presentation with one slide of each layout type."""
    return Presentation(
        metadata=PresentationMetadata(
            title="Test Export",
            author="Test Author",
            createdAt="2026-06-29T00:00:00Z",
        ),
        slides=[
            Slide(
                id="s1",
                layout=SlideLayout.TITLE,
                title="Test Presentation",
                subtitle="Generated by AI",
                body="June 2026",
            ),
            Slide(
                id="s2",
                layout=SlideLayout.TWO_COLUMN,
                title="Two Column Example",
                columns=Columns(
                    left=[
                        ContentBlock(type=ContentBlockType.HEADING, text="Left Side", level=2),
                        ContentBlock(type=ContentBlockType.PARAGRAPH, text="Some content here"),
                    ],
                    right=[
                        ContentBlock(type=ContentBlockType.HEADING, text="Right Side", level=2),
                        ContentBlock(type=ContentBlockType.PARAGRAPH, text="Other content here"),
                    ],
                ),
            ),
            Slide(
                id="s3",
                layout=SlideLayout.HIGHLIGHT_NUMBER,
                title="Key Metric",
                highlightNumber=HighlightNumber(value="99.9%", label="Uptime", suffix="+0.1%"),
                body=["Consistent performance", "Zero downtime incidents"],
            ),
            Slide(
                id="s4",
                layout=SlideLayout.TABLE,
                title="Quarterly Data",
                table=TableData(
                    headers=["Q1", "Q2", "Q3", "Q4"],
                    rows=[["$1M", "$1.2M", "$1.5M", "$2M"]],
                ),
            ),
            Slide(
                id="s5",
                layout=SlideLayout.BULLET_LIST,
                title="Key Points",
                body=["First point", "Second point", "Third point"],
            ),
        ],
    )


def test_generate_pptx_returns_bytes(sample_presentation):
    """PPTX generation should return non-empty bytes."""
    result = generate_pptx(sample_presentation)
    assert isinstance(result, bytes)
    assert len(result) > 0


def test_generate_pptx_valid_office_format(sample_presentation):
    """Generated file should start with the PPTX ZIP magic bytes."""
    result = generate_pptx(sample_presentation)
    # .pptx is a ZIP file — starts with PK (0x50 0x4B)
    assert result[:2] == b"PK"


def test_generate_pptx_minimal_presentation():
    """PPTX generation with a single slide should not fail."""
    pres = Presentation(
        metadata=PresentationMetadata(title="Minimal", createdAt="2026-01-01"),
        slides=[Slide(id="s1", layout=SlideLayout.TITLE, title="Hello")],
    )
    result = generate_pptx(pres)
    assert len(result) > 0
    assert result[:2] == b"PK"
